services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - pff-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pff-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092  # Utilisez l'adresse interne de votre broker
      - KAFKA_CLUSTERS_0_METRICS_PORT=9997
    depends_on:
      - kafka
    networks:
      - pff-network
      
  nifi:
    image: apache/nifi:1.23.2
    container_name: nifi
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=nifipassword123
      - NIFI_JVM_HEAP_INIT=4g
      - NIFI_JVM_HEAP_MAX=4g
    volumes:
      - ./data:/opt/nifi/nifi-current/data_in
      - ./data:/opt/nifi/nifi-current/data_out
    networks:
      - pff-network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - pff-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - pff-network

  mysql:
    image: mysql:8.0
    container_name: mysql_pff
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instacart_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pff-network

  adminer:
    image: adminer
    container_name: adminer_pff
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - pff-network

volumes:
  mysql_data:
networks:
  pff-network:
    driver: bridge